package dev.nohus.rift.network.requests

sealed class Endpoint(
    val isCounted: Boolean = true,
) {
    // ESI
    data object GetStatus : Endpoint()
    data object PostUniverseIds : Endpoint()
    data object PostUniverseNames : Endpoint()
    data object GetCharactersId : Endpoint()
    data object GetCharactersAffiliation : Endpoint()
    data object GetCorporationsId : Endpoint()
    data object GetAlliancesId : Endpoint()
    data object GetAlliancesIdContacts : Endpoint()
    data object GetCorporationsIdContacts : Endpoint()
    data object GetCharactersIdContacts : Endpoint()
    data object GetAlliancesIdContactsLabels : Endpoint()
    data object GetCorporationsIdContactsLabels : Endpoint()
    data object GetCharactersIdContactsLabels : Endpoint()
    data object DeleteCharactersIdContacts : Endpoint()
    data object PostCharactersIdContacts : Endpoint()
    data object PutCharactersIdContacts : Endpoint()
    data object GetCharacterIdOnline : Endpoint()
    data object GetCharacterIdShip : Endpoint()
    data object GetCharacterIdLocation : Endpoint()
    data object GetCharacterIdWallet : Endpoint()
    data object GetCharactersIdWalletJournal : Endpoint()
    data object GetCharactersIdWalletTransactions : Endpoint()
    data object GetCorporationsCorporationIdWallet : Endpoint()
    data object GetCorporationsCorporationIdWalletsDivisionJournal : Endpoint()
    data object GetCorporationsCorporationIdWalletsDivisionTransactions : Endpoint()
    data object GetCorporationsCorporationIdDivisions : Endpoint()
    data object GetCharactersIdSearch : Endpoint()
    data object GetCharactersIdClones : Endpoint()
    data object GetCharactersIdImplants : Endpoint()
    data object GetCharactersIdLoyaltyPoints : Endpoint()
    data object GetUniverseStationsId : Endpoint()
    data object GetUniverseStructuresId : Endpoint()
    data object GetUniverseSystemJumps : Endpoint()
    data object GetUniverseSystemKills : Endpoint()
    data object GetIncursions : Endpoint()
    data object GetFactionWarfareSystems : Endpoint()
    data object GetSovereigntyMap : Endpoint()
    data object PostUiAutopilotWaypoint : Endpoint()
    data object GetCharactersIdAssets : Endpoint()
    data object GetCharactersIdAssetsNames : Endpoint()
    data object GetCharactersIdAssetsLocations : Endpoint()
    data object GetCorporationsIdAssets : Endpoint()
    data object GetCorporationsIdAssetsNames : Endpoint()
    data object GetCorporationsIdAssetsLocations : Endpoint()
    data object GetMarketsPrices : Endpoint()
    data object GetCharactersIdFleet : Endpoint()
    data object GetFleetsId : Endpoint()
    data object GetFleetsIdMembers : Endpoint()
    data object GetCharactersIdPlanets : Endpoint()
    data object GetCharactersIdPlanetsId : Endpoint()
    data object GetIndustrySystems : Endpoint()
    data object GetCorporationsIdProjects : Endpoint()
    data object GetCorporationsIdProjectsId : Endpoint()
    data object GetCorporationsIdProjectsIdContribution : Endpoint()
    data object GetCorporationsIdProjectsIdContributors : Endpoint()
    data object GetFreelanceJobs : Endpoint()
    data object GetFreelanceJobsId : Endpoint()
    data object GetCharactersIdFreelanceJobs : Endpoint()
    data object GetCharactersIdFreelanceJobsIdParticipation : Endpoint()
    data object GetCorporationsIdFreelanceJobs : Endpoint()
    data object GetCorporationsIdFreelanceJobsIdParticipants : Endpoint()
    data object GetCharactersIdRoles : Endpoint()
    data object PostUiOpenWindowInformation : Endpoint()
    data object PostUiOpenWindowMarketDetails : Endpoint()
    data object PostUiOpenWindowNewMail : Endpoint()
    data object GetKillmail : Endpoint()

    // Image Service
    data object ImageServiceHeadCharacterPortrait : Endpoint()
    data object ImageServiceGetAllianceLogo : Endpoint()
    data object ImageServiceGetCorporationLogo : Endpoint()
    data object ImageServiceAsset : Endpoint()

    // Other APIs
    data object ADashboard : Endpoint()
    data object DscanInfo : Endpoint()
    data object EveScoutRescue : Endpoint()
    data object Zkillboard : Endpoint()
    data object ZkillboardListen : Endpoint(isCounted = true)
    data object Pushover : Endpoint()
    data object Ntfy : Endpoint()
    data object PostHog : Endpoint()

    // Raw requests
    data object Raw : Endpoint()
}
