package dev.nohus.rift.network.requests

sealed class RateLimitGroup(val name: String) {
    data object Status : RateLimitGroup("status")
    data object StaticData : RateLimitGroup("static-data")
    data object Character : RateLimitGroup("character")
    data object Corporation : RateLimitGroup("corporation")
    data object Alliance : RateLimitGroup("alliance")
    data object AllianceSocial : RateLimitGroup("alliance-social")
    data object CorpSocial : RateLimitGroup("corp-social")
    data object CorpProject : RateLimitGroup("corp-project")
    data object CharSocial : RateLimitGroup("char-social")
    data object CharLocation : RateLimitGroup("char-location")
    data object CharWallet : RateLimitGroup("char-wallet")
    data object CorpWallet : RateLimitGroup("corp-wallet")
    data object CharDetail : RateLimitGroup("char-detail")
    data object Incursion : RateLimitGroup("incursion")
    data object FactionalWarfare : RateLimitGroup("factional-warfare")
    data object Sovereignty : RateLimitGroup("sovereignty")
    data object Ui : RateLimitGroup("ui")
    data object CharAsset : RateLimitGroup("char-asset")
    data object CorpAsset : RateLimitGroup("corp-asset")
    data object Market : RateLimitGroup("market")
    data object Fleet : RateLimitGroup("fleet")
    data object CharIndustry : RateLimitGroup("char-industry")
    data object Industry : RateLimitGroup("industry")
    data object Killmail : RateLimitGroup("killmail")
    data object FreelanceJob : RateLimitGroup("freelance-job")
    data object CharFreelanceJob : RateLimitGroup("char-freelance-job")
    data object CorpFreelanceJob : RateLimitGroup("corp-freelance-job")
}
