// <auto-generated />
using System;
using EVEMakeMoney.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVEMakeMoney.Api.Migrations
{
    [DbContext(typeof(EVEMakeMoneyDbContext))]
    [Migration("20260223075931_AddProductionLines")]
    partial class AddProductionLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EVEMakeMoney.Api.Data.BlueprintEntity", b =>
                {
                    b.Property<long>("BlueprintTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TE")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlueprintTypeId");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.CalculationHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvancedIndustryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndustryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ME")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ManufacturingCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ManufacturingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReactionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReactionRigBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReactionStructureBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RigBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StructureBonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("TE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CalculationHistory");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AllianceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllianceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterOwnerHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporationName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("UserId", "CharacterId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.MarketHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Highest")
                        .HasColumnType("REAL");

                    b.Property<double>("Lowest")
                        .HasColumnType("REAL");

                    b.Property<long>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "RegionId", "Date")
                        .IsUnique();

                    b.ToTable("MarketHistory");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.MarketOrderEntity", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuyOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Issued")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinVolume")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Range")
                        .HasColumnType("TEXT");

                    b.Property<long>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VolumeRemain")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VolumeTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("MarketOrders");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.ProductionLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.UserBlueprintSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TE")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BlueprintTypeId")
                        .IsUnique();

                    b.ToTable("UserBlueprintSettings");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.WeeklySalesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double>("HighestPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("LowestPrice")
                        .HasColumnType("REAL");

                    b.Property<long>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalVolume")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "RegionId", "Year", "WeekNumber")
                        .IsUnique();

                    b.ToTable("WeeklySales");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.CharacterEntity", b =>
                {
                    b.HasOne("EVEMakeMoney.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVEMakeMoney.Api.Data.ProductionLineEntity", b =>
                {
                    b.HasOne("EVEMakeMoney.Api.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVEMakeMoney.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
