// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var blueprint = Blueprint.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Blueprint
    {
        [JsonProperty("_key")]
        public long Key { get; set; }

        [JsonProperty("activities")]
        public Activities Activities { get; set; }

        [JsonProperty("blueprintTypeID")]
        public long BlueprintTypeId { get; set; }

        [JsonProperty("maxProductionLimit")]
        public long MaxProductionLimit { get; set; }
    }

    public partial class Activities
    {
        [JsonProperty("copying", NullValueHandling = NullValueHandling.Ignore)]
        public Copying Copying { get; set; }

        [JsonProperty("invention", NullValueHandling = NullValueHandling.Ignore)]
        public Invention Invention { get; set; }

        [JsonProperty("manufacturing", NullValueHandling = NullValueHandling.Ignore)]
        public Manufacturing Manufacturing { get; set; }

        [JsonProperty("reaction", NullValueHandling = NullValueHandling.Ignore)]
        public Reaction Reaction { get; set; }

        [JsonProperty("research_material", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchMaterial ResearchMaterial { get; set; }

        [JsonProperty("research_time", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchTime ResearchTime { get; set; }
    }

    public partial class Copying
    {
        [JsonProperty("materials", NullValueHandling = NullValueHandling.Ignore)]
        public CopyingMaterial[] Materials { get; set; }

        [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
        public CopyingSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class CopyingMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class CopyingSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class Invention
    {
        [JsonProperty("materials", NullValueHandling = NullValueHandling.Ignore)]
        public InventionMaterial[] Materials { get; set; }

        [JsonProperty("products", NullValueHandling = NullValueHandling.Ignore)]
        public InventionProduct[] Products { get; set; }

        [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
        public InventionSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class InventionMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class InventionProduct
    {
        [JsonProperty("probability", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxValueCheckConverter))]
        public double? Probability { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class InventionSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class Manufacturing
    {
        [JsonProperty("materials", NullValueHandling = NullValueHandling.Ignore)]
        public ManufacturingMaterial[] Materials { get; set; }

        [JsonProperty("products", NullValueHandling = NullValueHandling.Ignore)]
        public ManufacturingProduct[] Products { get; set; }

        [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
        public ManufacturingSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class ManufacturingMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ManufacturingProduct
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ManufacturingSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class Reaction
    {
        [JsonProperty("materials")]
        public ReactionMaterial[] Materials { get; set; }

        [JsonProperty("products")]
        public ReactionProduct[] Products { get; set; }

        [JsonProperty("skills")]
        public ReactionSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class ReactionMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ReactionProduct
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ReactionSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ResearchMaterial
    {
        [JsonProperty("materials", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchMaterialMaterial[] Materials { get; set; }

        [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchMaterialSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class ResearchMaterialMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ResearchMaterialSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ResearchTime
    {
        [JsonProperty("materials", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchTimeMaterial[] Materials { get; set; }

        [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
        public ResearchTimeSkill[] Skills { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }
    }

    public partial class ResearchTimeMaterial
    {
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class ResearchTimeSkill
    {
        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("typeID")]
        public long TypeId { get; set; }
    }

    public partial class Blueprint
    {
        public static Blueprint FromJson(string json) => JsonConvert.DeserializeObject<Blueprint>(json, QuickType.Converter.Settings);

        public decimal ManufacturingCost { get; set; }

        public decimal ManufacturingTime { get; set; }

        public decimal InventionCost { get; set; }

        public int ME { get; set; }

        public int TE { get; set; }
    }

    public static class Serialize
    {
        public static string ToJson(this Blueprint self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class MinMaxValueCheckConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(double) || t == typeof(double?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<double>(reader);
            if (value >= 0.14 && value <= 0.34)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type double");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (double)untypedValue;
            if (value >= 0.14 && value <= 0.34)
            {
                serializer.Serialize(writer, value);
                return;
            }
            throw new Exception("Cannot marshal type double");
        }

        public static readonly MinMaxValueCheckConverter Singleton = new MinMaxValueCheckConverter();
    }
}